"""Core implementation and public interfaces for TRIM."""

from .TRIM_prototype_pipeline import TrimPipelineResult, run_trim_pipeline
from .dataset_registry import (
    DATASETS,
    build_data_loader,
    resolve_dataset,
    resolve_generalization_tree,
)
from .release_artifacts import (
    load_dataset_split,
    load_trim_release,
    materialize_trim_release,
)
from .experiment_hooks import (
    ALL_ROWS_AT_MAX_GENERALIZATION,
    EVICT_LOW_K_POSTPROCESSING,
    FULL_SWAP_POSTPROCESSING,
    NO_VERTICAL_POSTPROCESSING,
    RETENTION_CLASS_ACTION,
    S0_INITIALIZATION,
    VERTICAL_REFINEMENT_ACTION,
    AblationActions,
    CandidateObservation,
    CandidateObserver,
    CandidateScorerRunContext,
    CandidateShortlist,
    CandidateShortlistContext,
    CandidateStateScoreContext,
    CandidateStateScorer,
    CandidateStateScorerFactory,
    TRIMIterationObservation,
    TRIMIterationObserver,
    FixedRowCandidateBuilder,
    FixedRowCandidateBuilderContext,
    FixedRowCandidatePlan,
    RankedCandidate,
    SelectionScore,
    SelectionScoreContext,
    default_selection_score,
)

__all__ = [
    "ALL_ROWS_AT_MAX_GENERALIZATION",
    "AblationActions",
    "CandidateObservation",
    "CandidateObserver",
    "CandidateScorerRunContext",
    "CandidateShortlist",
    "CandidateShortlistContext",
    "CandidateStateScoreContext",
    "CandidateStateScorer",
    "CandidateStateScorerFactory",
    "DATASETS",
    "EVICT_LOW_K_POSTPROCESSING",
    "FULL_SWAP_POSTPROCESSING",
    "TRIMIterationObservation",
    "TRIMIterationObserver",
    "FixedRowCandidateBuilder",
    "FixedRowCandidateBuilderContext",
    "FixedRowCandidatePlan",
    "NO_VERTICAL_POSTPROCESSING",
    "RETENTION_CLASS_ACTION",
    "RankedCandidate",
    "S0_INITIALIZATION",
    "SelectionScore",
    "SelectionScoreContext",
    "TrimPipelineResult",
    "VERTICAL_REFINEMENT_ACTION",
    "build_data_loader",
    "load_dataset_split",
    "default_selection_score",
    "load_trim_release",
    "materialize_trim_release",
    "resolve_dataset",
    "resolve_generalization_tree",
    "run_trim_pipeline",
]
